name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to ECR Public
        run: |
          aws ecr-public get-login-password \
            --region us-east-1 | \
          docker login --username AWS \
            --password-stdin public.ecr.aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Build and push Docker image to ECR
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t public.ecr.aws/${{ secrets.ID_ECR }}/carlos-backend-api:latest \
            ./backend --push

      - name: SSH into EC2 and apply Kubernetes backend.yaml
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd devops-test
            git pull origin main
            sudo kubectl apply -f backend.yaml
